const SET_ALL_CARDS = 'SET_ALL_CARDS';
const ADD_CARD = "ADD_CARD";
const DELETE_CARD = "DELETE_CARD";
const ADD_DECK = "ADD_DECK";
const SET_ALL_DECKS = "SET_ALL_DECKS";
const DELETE_DECK = "DELETE_DECK";
const SAVE_CARD = "SAVE_CARD";
const SAVE_DECK = "SAVE_DECK";
const SET_USER = "SET_USER"


export default { SET_ALL_CARDS, ADD_CARD, DELETE_CARD, ADD_DECK, SET_ALL_DECKS, DELETE_DECK, SAVE_CARD, SAVE_DECK, SET_USER };